<script>
  let data = [
    {
      year: 1750,
      population: 220000,
      population_pixels: 17
    },
    {
      year: 1760,
      population: 310000,
      population_pixels: 26
    },
    {
      year: 1770,
      population: 462000,
      population_pixels: 38
    },
    {
      year: 1780,
      population: 562000,
      population_pixels: 59
    },
    {
      year: 1790,
      population: 757208,
      population_pixels: 80
    },
    {
      year: 1800,
      population: 1002037,
      population_pixels: 106
    },
    {
      year: 1810,
      population: 1377808,
      population_pixels: 132
    },
    {
      year: 1820,
      population: 1771656,
      population_pixels: 162
    },
    {
      year: 1830,
      population: 2328642,
      population_pixels: 194
    },
    {
      year: 1840,
      population: 2873648,
      population_pixels: 223
    },
    {
      year: 1850,
      population: 3638808,
      population_pixels: 255
    },
    {
      year: 1860,
      population: 4441830,
      population_pixels: 278
    },
    {
      year: 1870,
      population: 4880009,
      population_pixels: 311
    },
    {
      year: 1880,
      population: 6580793,
      population_pixels: 359
    },
    {
      year: 1890,
      population: 7470040,
      population_pixels: 407
    }
  ]

  // label position variables
  let yMarginTop = 18
  let yMarginBottom = 40
  let yearXPosition = 22.5
  let separatorXPosition = 70
  let populationXPosition = 153

  // bar variables
  let barXPosition = 165
  let barHeight = 11

  function yPos (index) {
    return yMarginTop + index * yMarginBottom
  }
</script>


<div class="graph">
  <div class="title">
    <!-- title/header content goes here -->
    <h1>
      Increase of the Negro population in the United States of America.
    </h1>
    <h2>
      Accroissement de la population Negre aux Etats Unis d' Amerique.
    </h2>
    <h3>Done by Atlanta University</h3>
  </div>
  <div class="main-chart">
    <!-- main chart -->
    <svg id="chart" width="900" height="600">
      {#each data as item, i}
        <g>
          <text class="graph-text" x={yearXPosition} y={yPos(i)} dy={10}>{item.year}</text>
          <text class="graph-text" x={separatorXPosition} y={yPos(i)} dy={10}>–</text>
          <text class="graph-text" x={populationXPosition} y={yPos(i)} dy={10} text-anchor="end">
            {item.population}
          </text>
          <rect class="bar" x={barXPosition} y={yPos(i)} height={barHeight} width={item.population_pixels} />
        </g>
      {/each}
      </svg>
  </div>
</div>

<div class="caption">
  <!-- footer content goes here -->
  <p>
    <span class="plateTitle">Plate 39</span>Population is a common subject
    of many of the charts generated by the Atlanta University team. The data
    set depicted here is unique in that it covers a span of 140 years. This
    chart also deploys both old-style typography and engineered templated
    lettering.
  </p>
</div>

<style>
  /* header styling */
  h1,
  h2,
  h3 {
    font-family: "Spectral", serif;
    font-weight: 200;
    text-align: center;
    color: rgb(60, 60, 60);
  }

  h1 {
    font-size: 20px;
  }

  h2 {
    font-size: 16px;
  }

  h3 {
    font-size: 14px;
  }

  /* overall graph dimensions */
  .graph {
    width: 750px;
    background-color: rgb(250, 239, 233);
    padding: 10px;
  }

  .title {
    width: 600px;
  }

  /* graph elements */

  .graph-text {
    font-family: "Teko", sans-serif;
    font-weight: 600;
    font-size: 15px;
    fill: rgb(60, 60, 60);
  }

  .bar {
    fill: rgb(167, 68, 87);
  }

  /* footer styling */
  .caption {
    width: 250px;
  }

  .plateTitle {
    font-weight: 700;
    margin-right: 10px;
  }

  p {
    font-family: sans-serif;
    font-size: 12px;
    font-weight: 500;
  }

  svg {
    margin-top: 10px;
  }

</style>