export const elder_facilities = [
  {
    "PLANNING AREAS": "ANG MO KIO",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 3
  },
  {
    "PLANNING AREAS": "ANG MO KIO",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 9
  },
  {
    "PLANNING AREAS": "ANG MO KIO",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 2
  },
  {
    "PLANNING AREAS": "BEDOK",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 3
  },
  {
    "PLANNING AREAS": "BEDOK",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 5
  },
  {
    "PLANNING AREAS": "BEDOK",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 8
  },
  {
    "PLANNING AREAS": "BISHAN",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 2
  },
  {
    "PLANNING AREAS": "BISHAN",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 3
  },
  {
    "PLANNING AREAS": "BISHAN",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 6
  },
  {
    "PLANNING AREAS": "BOON LAY",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "BOON LAY",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "BOON LAY",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "BUKIT BATOK",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 2
  },
  {
    "PLANNING AREAS": "BUKIT BATOK",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 5
  },
  {
    "PLANNING AREAS": "BUKIT BATOK",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 6
  },
  {
    "PLANNING AREAS": "BUKIT MERAH",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 3
  },
  {
    "PLANNING AREAS": "BUKIT MERAH",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 19
  },
  {
    "PLANNING AREAS": "BUKIT MERAH",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 3
  },
  {
    "PLANNING AREAS": "BUKIT PANJANG",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "BUKIT PANJANG",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 1
  },
  {
    "PLANNING AREAS": "BUKIT PANJANG",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "BUKIT TIMAH",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 2
  },
  {
    "PLANNING AREAS": "BUKIT TIMAH",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 1
  },
  {
    "PLANNING AREAS": "BUKIT TIMAH",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 2
  },
  {
    "PLANNING AREAS": "CENTRAL WATER CATCHMENT",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "CENTRAL WATER CATCHMENT",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "CENTRAL WATER CATCHMENT",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "CHANGI",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 1
  },
  {
    "PLANNING AREAS": "CHANGI",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "CHANGI",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 2
  },
  {
    "PLANNING AREAS": "CHANGI BAY",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "CHANGI BAY",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "CHANGI BAY",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "CHOA CHU KANG",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 1
  },
  {
    "PLANNING AREAS": "CHOA CHU KANG",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 3
  },
  {
    "PLANNING AREAS": "CHOA CHU KANG",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 4
  },
  {
    "PLANNING AREAS": "CLEMENTI",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 1
  },
  {
    "PLANNING AREAS": "CLEMENTI",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 7
  },
  {
    "PLANNING AREAS": "CLEMENTI",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 2
  },
  {
    "PLANNING AREAS": "DOWNTOWN CORE",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 2
  },
  {
    "PLANNING AREAS": "DOWNTOWN CORE",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "GEYLANG",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 4
  },
  {
    "PLANNING AREAS": "GEYLANG",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 9
  },
  {
    "PLANNING AREAS": "GEYLANG",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 4
  },
  {
    "PLANNING AREAS": "HOUGANG",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 2
  },
  {
    "PLANNING AREAS": "HOUGANG",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 5
  },
  {
    "PLANNING AREAS": "HOUGANG",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 2
  },
  {
    "PLANNING AREAS": "JURONG EAST",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 3
  },
  {
    "PLANNING AREAS": "JURONG EAST",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 7
  },
  {
    "PLANNING AREAS": "JURONG EAST",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 2
  },
  {
    "PLANNING AREAS": "JURONG WEST",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 2
  },
  {
    "PLANNING AREAS": "JURONG WEST",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 11
  },
  {
    "PLANNING AREAS": "JURONG WEST",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 2
  },
  {
    "PLANNING AREAS": "KALLANG",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "KALLANG",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 10
  },
  {
    "PLANNING AREAS": "KALLANG",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "LIM CHU KANG",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "LIM CHU KANG",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "LIM CHU KANG",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "MANDAI",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "MANDAI",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "MANDAI",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "MARINA EAST",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "MARINA EAST",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "MARINA EAST",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "MARINA SOUTH",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "MARINA SOUTH",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "MARINA SOUTH",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "MARINE PARADE",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 3
  },
  {
    "PLANNING AREAS": "MARINE PARADE",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 1
  },
  {
    "PLANNING AREAS": "MARINE PARADE",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "MUSEUM",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "MUSEUM",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "MUSEUM",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "NEWTON",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "NEWTON",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "NEWTON",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "NOVENA",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 3
  },
  {
    "PLANNING AREAS": "NOVENA",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 2
  },
  {
    "PLANNING AREAS": "NOVENA",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 7
  },
  {
    "PLANNING AREAS": "ORCHARD",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "ORCHARD",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 1
  },
  {
    "PLANNING AREAS": "ORCHARD",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "OUTRAM",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 3
  },
  {
    "PLANNING AREAS": "OUTRAM",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 5
  },
  {
    "PLANNING AREAS": "OUTRAM",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "PASIR RIS",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "PASIR RIS",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "PASIR RIS",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 1
  },
  {
    "PLANNING AREAS": "PAYA LEBAR",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "PAYA LEBAR",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "PAYA LEBAR",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "PIONEER",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "PIONEER",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "PIONEER",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "PUNGGOL",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "PUNGGOL",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 2
  },
  {
    "PLANNING AREAS": "PUNGGOL",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 1
  },
  {
    "PLANNING AREAS": "QUEENSTOWN",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 4
  },
  {
    "PLANNING AREAS": "QUEENSTOWN",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 9
  },
  {
    "PLANNING AREAS": "QUEENSTOWN",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 1
  },
  {
    "PLANNING AREAS": "RIVER VALLEY",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "RIVER VALLEY",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "RIVER VALLEY",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "ROCHOR",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "ROCHOR",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "ROCHOR",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "SELETAR",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "SELETAR",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "SELETAR",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "SEMBAWANG",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 1
  },
  {
    "PLANNING AREAS": "SEMBAWANG",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 1
  },
  {
    "PLANNING AREAS": "SEMBAWANG",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 2
  },
  {
    "PLANNING AREAS": "SENGKANG",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 1
  },
  {
    "PLANNING AREAS": "SENGKANG",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 2
  },
  {
    "PLANNING AREAS": "SENGKANG",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 9
  },
  {
    "PLANNING AREAS": "SERANGOON",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 1
  },
  {
    "PLANNING AREAS": "SERANGOON",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 5
  },
  {
    "PLANNING AREAS": "SERANGOON",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 3
  },
  {
    "PLANNING AREAS": "SIMPANG",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "SIMPANG",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "SIMPANG",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "SINGAPORE RIVER",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "SINGAPORE RIVER",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "SINGAPORE RIVER",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "SOUTHERN ISLANDS",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "SOUTHERN ISLANDS",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "SOUTHERN ISLANDS",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "STRAITS VIEW",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "STRAITS VIEW",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "STRAITS VIEW",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "SUNGEI KADUT",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "SUNGEI KADUT",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "SUNGEI KADUT",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "TAMPINES",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 2
  },
  {
    "PLANNING AREAS": "TAMPINES",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "TAMPINES",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 4
  },
  {
    "PLANNING AREAS": "TANGLIN",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "TANGLIN",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "TANGLIN",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "TENGAH",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "TENGAH",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "TENGAH",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "TOA PAYOH",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 3
  },
  {
    "PLANNING AREAS": "TOA PAYOH",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 13
  },
  {
    "PLANNING AREAS": "TOA PAYOH",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 2
  },
  {
    "PLANNING AREAS": "TUAS",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "TUAS",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "TUAS",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "WESTERN WATER CATCHMENT",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "WESTERN WATER CATCHMENT",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "WESTERN WATER CATCHMENT",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "WOODLANDS",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 0
  },
  {
    "PLANNING AREAS": "WOODLANDS",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 9
  },
  {
    "PLANNING AREAS": "WOODLANDS",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 3
  },
  {
    "PLANNING AREAS": "YISHUN",
    "TYPE OF FACILITIES": "HOME CARE",
    TOTAL: 2
  },
  {
    "PLANNING AREAS": "YISHUN",
    "TYPE OF FACILITIES": "DAY CARE",
    TOTAL: 9
  },
  {
    "PLANNING AREAS": "YISHUN",
    "TYPE OF FACILITIES": "STAY IN",
    TOTAL: 4
  }
];
