<script>
  // label variables
  let yearLabel = '1750' // single quotes indicate these are 'string' values
  let populationLabel = '220,000'

  // label position variables
  let yPosition = 15 // numeric variable
  let yearXPosition = 22.5
  let separatorXPosition = 70
  let populationXPosition = 153

  // bar variables
  let barXPosition = 165
  let barHeight = 11
  let barWidth = 17
</script>

<div class="graph">
  <div class="title">
    <!-- title/header content goes here -->
    <h1>
      Increase of the Negro population in the United States of America.
    </h1>
    <h2>
      Accroissement de la population Negre aux Etats Unis d' Amerique.
    </h2>
    <h3>Done by Atlanta University</h3>
  </div>
  <div class="main-chart">
    <!-- main chart -->
    <svg id="chart" width="900" height="600">
      <g>
        <text class="graph-text" x="22.5" y="15" dominant-baseline="hanging">1750</text>
        <text class="graph-text" x="70" y="15" dominant-baseline="hanging">–</text>
        <text class="graph-text" x="153" y="15" dominant-baseline="hanging" text-anchor="end">
          220,000
        </text>
        <rect class="bar" x="165" y="15" height="11" width="17" />
      </g>
      </svg>
  </div>
</div>

<div class="caption">
  <!-- footer content goes here -->
  <p>
    <span class="plateTitle">Plate 39</span>Population is a common subject
    of many of the charts generated by the Atlanta University team. The data
    set depicted here is unique in that it covers a span of 140 years. This
    chart also deploys both old-style typography and engineered templated
    lettering.
  </p>
</div>

<style>
  /* header styling */
  h1,
  h2,
  h3 {
    font-family: "Spectral", serif;
    font-weight: 200;
    text-align: center;
    color: rgb(60, 60, 60);
  }

  h1 {
    font-size: 20px;
  }

  h2 {
    font-size: 16px;
  }

  h3 {
    font-size: 14px;
  }

  /* overall graph dimensions */
  .graph {
    width: 750px;
    background-color: rgb(250, 239, 233);
    padding: 10px;
  }

  .title {
    width: 600px;
  }

  /* graph elements */

  .graph-text {
    font-family: "Teko", sans-serif;
    font-weight: 600;
    font-size: 15px;
    fill: rgb(60, 60, 60);
  }

  .bar {
    fill: rgb(167, 68, 87);
  }

  /* footer styling */
  .caption {
    width: 250px;
  }

  .plateTitle {
    font-weight: 700;
    margin-right: 10px;
  }

  p {
    font-family: sans-serif;
    font-size: 12px;
    font-weight: 500;
  }

  svg {
    margin-top: 10px;
  }

</style>